title: Long Do
description: Automation QE
theme: just-the-docs

url: https://longdohust.github.io/nang-am-xa-dan

aux_links:
  Template Repository: https://github.com/longdohust/nang-am-xa-dan
# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
